python main.py --dataset=AD_amazon_electronics_computers --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=0.001 --normal_weights=1.0 --seed=1
python main.py --dataset=AD_amazon_electronics_computers --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=0.001 --normal_weights=1.0 --seed=2
python main.py --dataset=AD_amazon_electronics_computers --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=0.001 --normal_weights=1.0 --seed=3
python main.py --dataset=AD_amazon_electronics_computers --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=0.001 --normal_weights=1.0 --seed=4
python main.py --dataset=AD_amazon_electronics_computers --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=0.001 --normal_weights=1.0 --seed=5
python main.py --dataset=AD_amazon_electronics_computers --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=0.001 --normal_weights=1.0 --seed=6
python main.py --dataset=AD_amazon_electronics_computers --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=0.001 --normal_weights=1.0 --seed=7
python main.py --dataset=AD_amazon_electronics_computers --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=0.001 --normal_weights=1.0 --seed=8
python main.py --dataset=AD_amazon_electronics_computers --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=0.001 --normal_weights=1.0 --seed=9
python main.py --dataset=AD_amazon_electronics_computers --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=0.001 --normal_weights=1.0 --seed=10
python main.py --dataset=AD_amazon_electronics_photo --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=50 --cluster_min_threshold=30  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=1000 --normal_weights=1.0 --seed=1
python main.py --dataset=AD_amazon_electronics_photo --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=50 --cluster_min_threshold=30  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=1000 --normal_weights=1.0 --seed=2
python main.py --dataset=AD_amazon_electronics_photo --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=50 --cluster_min_threshold=30  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=1000 --normal_weights=1.0 --seed=3
python main.py --dataset=AD_amazon_electronics_photo --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=50 --cluster_min_threshold=30  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=1000 --normal_weights=1.0 --seed=4
python main.py --dataset=AD_amazon_electronics_photo --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=50 --cluster_min_threshold=30  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=1000 --normal_weights=1.0 --seed=5
python main.py --dataset=AD_amazon_electronics_photo --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=50 --cluster_min_threshold=30  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=1000 --normal_weights=1.0 --seed=6
python main.py --dataset=AD_amazon_electronics_photo --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=50 --cluster_min_threshold=30  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=1000 --normal_weights=1.0 --seed=7
python main.py --dataset=AD_amazon_electronics_photo --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=50 --cluster_min_threshold=30  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=1000 --normal_weights=1.0 --seed=8
python main.py --dataset=AD_amazon_electronics_photo --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=50 --cluster_min_threshold=30  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=1000 --normal_weights=1.0 --seed=9
python main.py --dataset=AD_amazon_electronics_photo --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=10 --nodes_in_cluster=100  --cluster_split_threshold=50 --cluster_min_threshold=30  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.0001 --abnormal_weights=1000 --normal_weights=1.0 --seed=10
python main.py --dataset=AD_ms_academic_cs --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=20 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.001 --abnormal_weights=10 --normal_weights=1.0 --seed=1
python main.py --dataset=AD_ms_academic_cs --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=20 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.001 --abnormal_weights=10 --normal_weights=1.0 --seed=2
python main.py --dataset=AD_ms_academic_cs --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=20 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.001 --abnormal_weights=10 --normal_weights=1.0 --seed=3
python main.py --dataset=AD_ms_academic_cs --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=20 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.001 --abnormal_weights=10 --normal_weights=1.0 --seed=4
python main.py --dataset=AD_ms_academic_cs --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=20 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.001 --abnormal_weights=10 --normal_weights=1.0 --seed=5
python main.py --dataset=AD_ms_academic_cs --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=20 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.001 --abnormal_weights=10 --normal_weights=1.0 --seed=6
python main.py --dataset=AD_ms_academic_cs --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=20 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.001 --abnormal_weights=10 --normal_weights=1.0 --seed=7
python main.py --dataset=AD_ms_academic_cs --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=20 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.001 --abnormal_weights=10 --normal_weights=1.0 --seed=8
python main.py --dataset=AD_ms_academic_cs --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=20 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.001 --abnormal_weights=10 --normal_weights=1.0 --seed=9
python main.py --dataset=AD_ms_academic_cs --max_used_seen_anomalies=20  --outlier_clu_num=1 --ratio_labeled_normal=0.1 --total_clu_num=20 --nodes_in_cluster=100  --cluster_split_threshold=100  --whether_aug=True --data_aug_factor=1 --feature_extractor=GCN --labeld_seen_outliers_num=20 --lr=0.001 --abnormal_weights=10 --normal_weights=1.0 --seed=10
